### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by RadValentin** [RadValentin/starwind#6]
## Need

Remove anything that's unneeded from the repo, optimize for smaller footprint and better performance where possible

#### TODO

- [x] Stop tracking CSS, this shouldn't be in the repo
- [x] Add dev/prod parameter to build task, determines whether to include sourcemaps
- [x] Remove any unused files
- [x] Drop Series Options plugin's custom CSS (disable in WP admin) and write custom CSS for it
- [x] Drop Font Awesome CSS source, replace with SASS
- [x] Drop Bootstrap CSS source
  - [x] Replace it with SASS source
  - [x] Only include the parts of BS that are being used
- [x] Fix any visual bugs caused by CSS removal 
- [ ] Remove stars CSS animation and replace it with canvas implementation (performance++)
- [ ] Remove static assets from front-page and replace with wordpress-friendly implementation
- [ ] Cross-browser test everything (IE8+)
